# Generated by Django 4.1.7 on 2023-03-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adoption_center_register',
            fields=[
                ('aid_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('agency_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mail_id', models.CharField(max_length=50)),
                ('place_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_agency_register',
            },
        ),
        migrations.CreateModel(
            name='adoption_info',
            fields=[
                ('adoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_type', models.CharField(max_length=50)),
                ('tag_name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('photo', models.CharField(max_length=50)),
                ('Ac_login_id', models.IntegerField()),
                ('status', models.CharField(default='Not Adopted', max_length=50)),
                ('adopted_user_login_id', models.IntegerField(default=0)),
                ('rescue_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_adoption',
            },
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_subject', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=150)),
                ('user_login_id', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_country',
            },
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_district',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_subject', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=150)),
                ('Ac_login_id', models.IntegerField()),
                ('user_login_id', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.TextField(null=True)),
                ('Usertype', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('age', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('user_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_pets',
            },
        ),
        migrations.CreateModel(
            name='Rescue_info',
            fields=[
                ('rescue_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('Ac_login_id', models.IntegerField()),
                ('user_login_id', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_rescue',
            },
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mail_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_user_register',
            },
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetRescueApp.country')),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetRescueApp.district')),
            ],
            options={
                'db_table': 'tbl_place',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetRescueApp.state'),
        ),
    ]
