# Generated by Django 4.1.7 on 2023-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetRescueApp', '0002_boarding_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='grooming_service',
            fields=[
                ('g_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=0)),
                ('Ac_login_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_grooming_service',
            },
        ),
    ]
