# Generated by Django 4.1.7 on 2023-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetRescueApp', '0003_grooming_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_boarding',
            fields=[
                ('boarding_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('pet_id', models.IntegerField()),
                ('b_service_id', models.IntegerField()),
                ('user_login_id', models.IntegerField()),
                ('status', models.CharField(default='Not Accepted', max_length=50)),
            ],
            options={
                'db_table': 'tbl_booking_boarding',
            },
        ),
    ]
