# Generated by Django 4.1.7 on 2023-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetRescueApp', '0004_booking_boarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_grooming',
            fields=[
                ('grroming_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pet_id', models.IntegerField()),
                ('g_service_id', models.IntegerField()),
                ('user_login_id', models.IntegerField()),
                ('status', models.CharField(default='Not Accepted', max_length=50)),
            ],
            options={
                'db_table': 'tbl_booking_grooming',
            },
        ),
    ]
